version: 0.2

phases:
  pre_build:
    commands:
      - echo $CODEBUILD_SOURCE_VERSION
      - PULL_REQUEST=true
      - echo $CODEBUILD_SOURCE_VERSION | grep -q "pr" || PULL_REQUEST=false
      - if $PULL_REQUEST; then exit 0; fi
  build:
    commands:
      - apt-get update -y
